### ISSUE TITLE
Can't get addon to modify Content-Type response header

### ISSUE THREAD

**Issue by cstroe** [warren-bank/fork-moz-modifyheaders-response#1]
I have the following setup:

<img width="625" alt="screen shot 2017-06-17 at 11 14 06 am" src="https://user-images.githubusercontent.com/1182093/27254468-2890acb0-534e-11e7-8cb1-68d7cf6aba58.png">

However, when I browse to an endpoint that returns something else for `Content-Type`, it doesn't modify it.

<img width="912" alt="screen shot 2017-06-17 at 11 15 50 am" src="https://user-images.githubusercontent.com/1182093/27254494-05831e6e-534f-11e7-9ae5-1376bc1dd6f3.png">

Is there anything I'm doing wrong?

**Comment by warren-bank** [comment]
Hi, I haven't attempted to reproduce your error (because I don't use Firefox any longer).. but I trust you.

As recently discussed [here](https://github.com/warren-bank/moz-json-data-view/issues/14), which I'm sure all previous authors of addons will be hearing about (ad nauseam) until Firefox v57  refuses to install them all-together, I would guess that this is part of the downward spiral of support for (non-Chromium.. oops, I mean: non-"WebExtension") addons.

Multi-process might be breaking some aspect of compatibility. I stress "_might_".. idk.. could dig into it.. but not going to. Imho, Firefox is dead (long live Firefox).

**Comment by warren-bank** [comment]
As for your specific use-case, I wanted to offer the alternate suggestion/workaround:
[Open in Browser](https://addons.mozilla.org/en-us/firefox/addon/open-in-browser/)
..but that addon's compatibility ended with FF v32
..so much for that

My other addon for slicing and dicing HTTP headers is [moz-rewrite](https://addons.mozilla.org/en-us/firefox/addon/moz-rewrite-json/), but it uses the exact same API hooks as the addon in this repo. So, if one isn't working.. I'd assume the same of the other.

Yeah, my only advise at this point would be to jump ship.. if Firefox wants all of its architectural/design decisions as well as APIs to perfectly mimic those of Chromium.. I can't think of a single reason to prevent everybody from simply opting to use Chromium instead.. which always does things first, and always implements things better. Firefox had an amazing ecosystem, but it's gone now. Mozilla had a noble philosophy, but for years it has been saying one thing.. then doing another.

**Comment by stewie** [comment]
original post didn't mention which firefox version. I tested using ff45-esr and found the Rule (modify: Content-Type: application/json) is "successful" ~~ as confirmed by viewing headers via LiveHTTPheaders addon ~~ yet yields no changed result in browser behavior, in the sense that whatever document is returned by (for instance) "https://ebay.com"... still winds up being rendered as an html document. I'm not presented with an "OpenWith / Save" dialog.

**Comment by warren-bank** [comment]
ok, well.. assuming that both comments are from the same user (or team).. I guess my original assertion that I should take the error on face value was false.

sounds like the addon is still working.. no compatibility issue.

here's a question:
Is the content of the response valid JSON data?
ie: would `JSON.parse()` succeed or fail?

if not, then..
by default, "application/json" is rendered by the browser.
In older browsers, it would render as "text/plain".
In newer browsers (not sure about v45), it would render in a (native) JSON viewer.
How such a viewer would respond to non-JSON data is (I believe) the root of your issue.
I would guess that if parsing were to fail, then it would attempt to make a best-effort guess at what the content is. Such an algorithm would probably start by testing with a regex pattern match against a doctype or opening `<html>` tag to detect an html document, and then render it as "text/html". Is there any chance that may be what's happening?

in any case, try adding a `"content-disposition"` header and see if that solves what you're trying to do. It'll ignore `"content-type"` and prompt you to save the file, regardless.

**Comment by warren-bank** [comment]
[here](http://headers.jsontest.com/?mime=1) is a test URL that return JSON data with `{"content-type": "application/json"}`

**Comment by warren-bank** [comment]
this [article](https://www.ghacks.net/2017/01/12/firefox-53-json-viewer-on-by-default/) says that Firefox's native JSON viewer was introduced in v44 but wasn't turned on by default until v53.

when you load the above url, does it show as plain text or in a (really ugly) viewer UI?

**Comment by warren-bank** [comment]
I gave this addon a quick install and test drive in: Firefox 53.0 (64-bit, Ubuntu)

* `Content-Disposition: attachment; filename="filename.txt"` works good
* `Content-Type: text/plain` causes no response headers to be modified.. it even prevents the "content-disposition" from being added (which triggers a "save as" dialog)

so.. bug confirmed.
I'm not sure when this was introduced..

I may quickly install "moz-rewrite" and test whether "content-type" can be modified.
I know for a fact that it worked in that addon.

**Comment by warren-bank** [comment]
nope.. no joy there either.

Firefox changed the low-level API (yet again).

log of error message, copied from "Tools > Web Developer > Browser Console":
```text
NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057
(NS_ERROR_ILLEGAL_VALUE) [nsIHttpChannel.setResponseHeader]
```

This is the culprit for both addons.
Presumably, "content-type" is now a __protected__ header, and attempting to intercept and change its value throws an Exception. That never used to be the case. Not sure if it's documented anywhere, but.. that's the way Firefox goes.

**Comment by warren-bank** [comment]
too funny..

the official docs for [nsIHttpChannel.setResponseHeader](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIHttpChannel#setResponseHeader()) uses "content-type" in its example (when discussing "merge").

so.. it should work, it used to work, but they broke it.

**Comment by warren-bank** [comment]
my final comment is an observation of something odd..

if I load this [url](http://headers.jsontest.com/?mime=2),
which the server responds with: `content-type: application/js`

while either of the addons are actively trying to change this "content-type" to: "plain/text"

and I closely watch the "network" panel as the file loads,
I can observe its "type" change:
`js` > `plain` > `js`

**Comment by warren-bank** [comment]
oops, forget what I just said about being able to watch the "content-type" change and then revert.

"text/plain" is (apparently) a bad/deceptive test case. I tried to coerce the type to something else, and saw the exact same behavior.

i suppose that all network files are initially plain text briefly.. until Firefox inspects the response header and updates the value.

**Comment by warren-bank** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1232849

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Necko

**Comment by cstroe** [comment]
For completeness:

<img width="649" alt="screen shot 2017-06-19 at 6 13 52 pm" src="https://user-images.githubusercontent.com/1182093/27309709-1d6c6a62-551b-11e7-83b0-4b27f73e3513.png">

Mozilla Firefox 54 on macOS 10.12.5

**Comment by warren-bank** [comment]
I thought I'd found the root of the problem..

Here's the [source code in Firefox](https://github.com/mozilla/gecko-dev/blob/4948ad52d692d1decb768947abd06073b8636b37/netwerk/protocol/http/HttpBaseChannel.cpp#L1677) that causes the API to throw an Error:

```cpp
HttpBaseChannel::SetResponseHeader(const nsACString& header, ...){
  ...
  nsHttpAtom atom = nsHttp::ResolveAtom(header);
  ...
  if (atom == nsHttp::Content_Type ||
      atom == nsHttp::Content_Length ||
      atom == nsHttp::Content_Encoding ||
      atom == nsHttp::Trailer ||
      atom == nsHttp::Transfer_Encoding)
  return NS_ERROR_ILLEGAL_VALUE;
  ...
}
```

Figured that I could look at the [history of this file](https://github.com/mozilla/gecko-dev/commits/master/netwerk/protocol/http/HttpBaseChannel.cpp).. and pinpoint exactly when this conditional check was added. Problem is, it's been in the code since long before I wrote the addon. And even though this implementation of `SetResponseHeader` is in a base class, I can't find any classes that extend the class and override the implementation. Nevertheless, changing 'content-type' was one of the first tests that I ran while developing the addon.. and it always worked perfectly (at that time).

In any case...
none of this amounts to much, since the API is being removed from Firefox soon.

I guess the take-away is...
setting any of the above headers will throw an Error in recent versions of Firefox.

Personally...
if I wanted to use "legacy" addons,
I'd install an old copy of Firefox v47,
which was the final version that allowed the installation of unsigned addons:
* `about:config`
* `xpinstall.signatures.required` = false

then:
* test whether or not these headers can be changed
* if not, repeat with a slightly older version

another thought that just occured to me:
* all of my testing (at the time) was in Windows 7
  * home system configuration was setup to match the one at work
  * not there any longer, so now my default home system is Lubuntu
    * VirtualBox guest in a Fedora host
* point is, it may be a bug in Firefox that allows the addon to work in Windows
  * regardless of version?
  * I'll test this out later...
